# .github/workflows/deploy-pages.yaml
# Deploy to GitHub Pages
name: Reusable - Deploy to GitHub Pages

on:
  # Adding a workflow_call to make this workflow reusable
  workflow_call:
    # No inputs because they are passed in the artifact created by the calling function.

jobs:
  # This job's only responsibility is to deploy.
  deploy:
    name: Deploy to Pages
    # 1. Define the runner
    runs-on: ubuntu-latest
      # 2. Permissions are required for the deploy action to work.
    permissions:
      pages: write
      id-token: write
    # 3. The deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # 4. The steps to run
    steps:
      # It's best practice to use a more specific version of actions
      # to avoid unexpected breaking changes.
      # Deploy the artifact
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4               # 4. Deploy!